name: Auto Update Server

on:
  push:
    branches:
      - dev # Replace this with the branch you want to track, e.g., dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Passphrase-Protected Key
        env:
            SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
            echo "$SSH_PASSPHRASE" | ssh-add -

      # Step 3: Deploy changes to the server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin dev
          EOF
